server:
  port: 8091

clients:
  exchange:
    uri: ${CLIENT_EXCHANGE_URI}

spring:
  application:
    name: bank-exchange-generator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      properties:
        acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      client-id: bank-app
    consumer:
      properties:
        security.protocol: PLAINTEXT
    template:
      observation-enabled: true

management:
  zipkin:
    tracing:
      endpoint:  ${ZIPKIN_ENDPOINT}
  tracing:
    enabled: true
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus