server:
  port: 8091

clients:
  exchange:
    uri: ${CLIENT_EXCHANGE_URI}

spring:
  application:
    name: bank-exchange-generator
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      properties:
        acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      client-id: bank-app
    consumer:
      properties:
        security.protocol: PLAINTEXT
