server:
  port: 8091

clients:
  exchange:
    uri: ${gateway_service_url}

gateway_service_url: ${COMMON_SERVICE_API_URL}

spring:
  application:
    name: bank-exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
