server:
  port: 8091

clients:
  exchange:
    uri: ${gateway_service_url}

gateway_service_url: http://localhost:8081/api

spring:
  application:
    name: bank-exchange-generator
  cloud:
    config:
      uri: http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
