server:
  port: 8091

clients:
  exchange:
    uri: ${gateway_service_url}

gateway_service_url: http://bank-gateway:8081/api

spring:
  application:
    name: bank-exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm
