server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank
      client:
        registration:
          keycloak:
            client-id: bank-gateway
            client-secret: ${KEYCLOAK_GATEWAY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/bank-realm

keycloak:
  realm: bank
  auth-server-url: http://keycloak:8080
  resource: bank-auth-server
