server:
  port: 8089
spring:
  application:
    name: bank-cash
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm

gateway_service_url: http://localhost:8081/api

clients:
  accounts:
    uri: ${gateway_service_url}

eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka
