services:

  eureka-server:
    container_name: bank-eureka-server
    build:
      context: .
      dockerfile: bank-eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - bank-network

  config-server:
    container_name: bank-config-server
    build:
      context: .
      dockerfile: bank-config-server/Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - bank-network

networks:
  bank-network:
      driver: bridge