{{- if .Values.realmConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
data:
  realm.json: {{ .Files.Get .Values.realmConfig.realmFile | quote }}
{{- end }}
