server:
  port: 8095

spring:
  application:
    name: bank-notifications
  mail:
    host: smtp.example.com
    port: 587
    username: user@example.com
    password: secret
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm
eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka
