replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: latest
  pullPolicy: IfNotPresent

realmConfig:
  enabled: true
  realmFile: files/realm.json

persistence:
  enabled: true
  size: 1Gi

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: bank-keycloak.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]