apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-blocker.fullname" . }}-config
  labels:
    {{- include "bank-blocker.labels" . | nindent 4 }}
data:
  KEYCLOAK_ISSUER_URI: {{ tpl .Values.global.uri.keycloak_issuer . | quote }}
