apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-blocker.fullname" . }}
  labels:
    {{- include "bank-blocker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.blocker_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bank-blocker.selectorLabels" . | nindent 4 }}
