replicaCount: 1

image:
  repository: bank-cash
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

env:
  - name: LOGGING_LEVEL_ROOT
    value: DEBUG
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
    value: DEBUG
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_REACTIVE
    value: DEBUG
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CLIENT
    value: DEBUG
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
    value: INFO
  - name: LOGGING_LEVEL_RU_YANDEX_PRACTICUM_BANK
    value: DEBUG
