apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-accounts.fullname" . }}-config
  labels:
    {{- include "bank-accounts.labels" . | nindent 4 }}
data:
  KEYCLOAK_ISSUER_URI: {{ tpl .Values.config.keycloak_url . | quote }}
  SPRING_DATASOURCE_URL: {{ tpl .Values.config.database_url . | quote }}
  POSTGRESQL_USER: {{ .Values.postgresql.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | quote }}