server:
  port: 8097

spring:
  application:
    name: bank-blocker
  cloud:
    config:
      uri: http://bank-config-server:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm

eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka
