server:
  port: 8097

spring:
  application:
    name: bank-blocker
  cloud:
    config:
      uri: http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
