apiVersion: v2
name: bank-app
description: Umbrella chart for Bank App
version: 0.1.0

dependencies:
  - name: keycloak
    version: 1.0.0
    repository: file://charts/keycloak
  - name: postgresql
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami
  - name: bank-accounts
    version: "0.1.0"
    repository: file://charts/bank-accounts
  - name: bank-front-ui
    version: 0.1.0
    repository: file://charts/bank-front-ui
