apiVersion: v2
name: bank-app
description: Umbrella chart for Bank App
version: 0.1.0

dependencies:
  - name: keycloak
    version: 1.0.0
    repository: file://charts/keycloak
  - name: postgresql
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: 32.2.15
    repository: https://charts.bitnami.com/bitnami
  - name: bank-accounts
    version: 0.1.0
    repository: file://charts/bank-accounts
  - name: bank-front-ui
    version: 0.1.0
    repository: file://charts/bank-front-ui
  - name: bank-exchange
    version: 0.1.0
    repository: file://charts/bank-exchange
  - name: bank-exchange-generator
    version: 0.1.0
    repository: file://charts/bank-exchange-generator
  - name: bank-blocker
    version: 0.1.0
    repository: file://charts/bank-blocker
  - name: bank-notifications
    version: 0.1.0
    repository: file://charts/bank-notifications
  - name: bank-cash
    version: 0.1.0
    repository: file://charts/bank-cash
  - name: bank-transfer
    version: 0.1.0
    repository: file://charts/bank-transfer
  - name: bank-mailhog
    version: 0.1.0
    repository: file://charts/bank-mailhog
  - name: zipkin
    version: 1.3.5
    repository: https://charts.bitnami.com/bitnami
  - name: kube-prometheus-stack
    version: 58.1.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: logstash
    version: 8.5.1
    repository: https://helm.elastic.co
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: kibana.enabled