postgresql:
  image:
    tag: 17

  auth:
    username: postgres
    password: postgres
    database: postgres

  primary:
    initdb:
      scripts:
        init-multiple-dbs.sql: |-
          CREATE DATABASE accounts;
          CREATE DATABASE notifications;
          CREATE DATABASE cash;
          CREATE DATABASE exchange;
          CREATE DATABASE transfer;
  services:
    ports:
      postgresql: 5432

  persistence:
    enabled: true
    size: 500Mi
