global:
  ports:
    front_ui_port: 80
    mailhog_smtp_port: 1025
    mailhog_http_port: 8025
    keycloak_port: 8080
    accounts_port: 8082
    cash_port: 8089
    transfer_port: 8090
    exchange_generator_port: 8091
    exchange_port: 8093
    notifications_port: 8095
    blocker_port: 8097
  uri:
    keycloak_issuer: "http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.keycloak_port }}/realms/bank-realm"
    database: "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
  postgresql:
    username: postgres
    password: postgres
  keycloak:
    realm: "bank-realm"
  clients:
    client_account_uri: http://{{ .Release.Name }}-bank-accounts.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.accounts_port }}/api
    client_exchange_uri: http://{{ .Release.Name }}-bank-exchange.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.exchange_port }}/api

postgresql:
  image:
    tag: 17

  auth:
    username: postgres
    password: postgres
    database: postgres

  primary:
    initdb:
      scripts:
        init-multiple-dbs.sql: |-
          CREATE DATABASE accounts;
          CREATE DATABASE notifications;
          CREATE DATABASE cash;
          CREATE DATABASE exchange_rates;
          CREATE DATABASE transfers;
  services:
    ports:
      postgresql: 5432

  persistence:
    enabled: true
    size: 500Mi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: bank-app.local
      paths:
        - path: /api(/|$)(.*)
          pathType: Prefix

bank-accounts:
  image:
    repository: bank-accounts
    tag: latest
  ingress:
    enabled: true
    hostname: bank-accounts.local


bank-front-ui:
  image:
    repository: bank-front-ui
    tag: latest
  ingress:
    enabled: true
    hostname: bank-front-ui.local

bank-exchange:
  image:
    repository: bank-exchange
    tag: latest
  ingress:
    enabled: true
    hostname: bank-exchange.local

bank-exchange-generator:
  image:
    repository: bank-exchange-generator
    tag: latest
  ingress:
    enabled: true
    hostname: bank-exchange-generator.local
