postgresql:
  image:
    tag: 17

  auth:
    username: postgres
    password: postgres
    database: postgres

  primary:
    initdb:
      scripts:
        init-multiple-dbs.sql: |-
          CREATE DATABASE accounts;
          CREATE DATABASE notifications;
          CREATE DATABASE cash;
          CREATE DATABASE exchange_rates;
          CREATE DATABASE transfers;
  services:
    ports:
      postgresql: 5432

  persistence:
    enabled: true
    size: 500Mi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: bank-app.local
      paths:
        - path: /api(/|$)(.*)
          pathType: Prefix

bank-accounts:
  image:
    repository: bank-accounts
    tag: latest
  ingress:
    enabled: true
    hostname: bank-accounts.local


bank-front-ui:
  image:
    repository: bank-front-ui
    tag: latest
  ingress:
    enabled: true
    hostname: bank-front-ui.local

bank-exchange:
  image:
    repository: bank-exchange
    tag: latest
  ingress:
    enabled: true
    hostname: bank-exchange.local

bank-exchange-generator:
  image:
    repository: bank-exchange-generator
    tag: latest
  ingress:
    enabled: true
    hostname: bank-exchange-generator.local

mailhog:
  service:
    type: ClusterIP
    ports:
      smtp: 1025
      http: 8025

  ingress:
    enabled: true
    hostname: bank-mailhog.local
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    ingressClassName: nginx