apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-notifications.fullname" . }}
  labels:
    app: {{ include "bank-notifications.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.notifications_port }}
      targetPort: {{ .Values.global.ports.notifications_port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "bank-notifications.name" . }}
