apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-mailhog.fullname" . }}
spec:
  selector:
    app: {{ include "bank-mailhog.name" . }}
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
