apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-mailhog.fullname" . }}
spec:
  selector:
    app: {{ include "bank-mailhog.name" . }}
  ports:
    - name: smtp
      port: {{ .Values.global.ports.mailhog_smtp_port }}
      targetPort: {{ .Values.global.ports.mailhog_smtp_port }}
    - name: http
      port: {{ .Values.global.ports.mailhog_http_port }}
      targetPort: {{ .Values.global.ports.mailhog_http_port }}
