spring:
  config:
    import: configserver:http://config-server:8888
  application:
    name: bank-accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm
  r2dbc:
    url: r2dbc:postgresql://bank-postgres:5432/accounts
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  datasource:
    url: jdbc:postgresql://bank-postgres:5432/accounts
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    default-schema: public
    url: jdbc:postgresql://bank-postgres:5432/accounts
    user: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG