replicaCount: 1

image:
  repository: bank-front-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: { }
  hosts:
    - host: bank-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]