server:
  port: 8093

spring:
  application:
    name: bank-exchange
  cloud:
    config:
      uri: http://bank-config-server:8888
  config:
    import: optional:configserver:http://bank-config-server:8888
  r2dbc:
    url: r2dbc:postgresql://bank-postgres:5432/exchange_rates
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:postgresql://bank-postgres:5432/exchange_rates
    user: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    change-log: classpath:/db/changelog/db.changelog-master.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm

eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka
