server:
  port: 8093

spring:
  application:
    name: bank-exchange
  r2dbc:
    url: r2dbc:${SPRING_DATASOURCE_URL}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:${SPRING_DATASOURCE_URL}
    user: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    change-log: classpath:/db/changelog/db.changelog-master.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: exchange
      properties:
        spring.json.trusted.packages: ru.yandex.practicum.bank.*
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always