apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-transfer.fullname" . }}
  labels:
    {{- include "bank-transfer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.transfer_port }}
      targetPort: {{ .Values.global.ports.transfer_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "bank-transfer.selectorLabels" . | nindent 4 }}
