apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-transfer.fullname" . }}
  labels:
    app: {{ include "bank-transfer.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.transfer_port }}
      targetPort: {{ .Values.global.ports.transfer_port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "bank-transfer.name" . }}
