apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-exchange-generator.fullname" . }}-config
  labels:
    {{- include "bank-exchange-generator.labels" . | nindent 4 }}
data:
  KEYCLOAK_ISSUER_URI: {{ tpl .Values.config.keycloak_url . | quote }}
  CLIENT_EXCHANGE_URI: {{ tpl .Values.config.client_exchange_uri . | quote }}