apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-exchange-generator.fullname" . }}-config
  labels:
    {{- include "bank-exchange-generator.labels" . | nindent 4 }}
data:
  CLIENT_EXCHANGE_URI: {{ tpl .Values.global.clients.client_exchange_uri . | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ tpl .Values.global.kafka.url . | quote }}
  ZIPKIN_ENDPOINT: {{ tpl .Values.global.zipkin.url . | quote }}