# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibana.fullname" . }}-config
data:
  kibana.yml: |
    elasticsearch.ssl.verificationMode: none
    elasticsearch.hosts: ["https://elasticsearch:9200"]
    elasticsearch.serviceAccountToken: {{ .Values.elasticsearch.serviceAccountToken | quote }}
