replicaCount: 1

enabled: false

image:
  repository: docker.elastic.co/kibana/kibana
  tag: "8.18.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 5601
  nodePort: 32000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: bank-kibana.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

auth:
  elasticsearch:
    createDefaultToken: false
    username: ""
    password: ""

enterpriseSearch:
  enabled: false

elasticsearch:
  serviceAccountToken: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpBb1ktQjBOVFFzbWQ5UVB5ZmZyUUxB

extraEnvs: []

security:
  enabled: true

automountToken: false

lifecycleHooks:
  preInstall: []

